name: Compile and deploy Sphinx documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install sphinx nbsphinx sphinx-rtd-theme

    - name: Build HTML with Sphinx
      run: |
        cd docs
        make html

    
    - name: Clone gh-pages branch
      run: |
        git clone --branch gh-pages https://github.com/PREDICO-Project/MIMAC.git gh-pages
  
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || echo "No changes to commit"

    - name: Push changes to gh-pages
      run: |
        cd gh-pages
        git push origin gh-pages
