name: Compile and deploy Sphinx documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install sphinx nbsphinx sphinx-rtd-theme

    - name: Build HTML with Sphinx
      run: |
        cd docs
        make html

    - name: Clone gh-pages branch (or create if missing)
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git clone --branch gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/PREDICO-Project/MIMAC.git gh-pages || \
        (git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/PREDICO-Project/MIMAC.git gh-pages && \
         cd gh-pages && \
         git checkout --orphan gh-pages && \
         git rm -rf . && \
         touch .nojekyll && \
         git add .nojekyll && \
         git commit -m "Initialize gh-pages" && \
         git push origin gh-pages)

    - name: Copy HTML to gh-pages and commit
      run: |
        rm -rf gh-pages/*
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git add .
        git commit -m "Update documentation" -a || echo "No changes to commit"

    - name: Push to gh-pages
      run: |
        cd gh-pages
        git push origin gh-pages
